//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escolapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.CursoAlumno = new HashSet<CursoAlumno>();
        }
    
        public int id_alumno { get; set; }
        public int id_semestre { get; set; }
        public int id_especialidad { get; set; }
        public string nombre_alumno { get; set; }
        public string apellido_alumno { get; set; }
        public string direccion_alumno { get; set; }
        public int edad_alumno { get; set; }
        public string sexo_alumno { get; set; }
        public string telefono_alumno { get; set; }
        public System.DateTime fecha_registro_alumno { get; set; }
        public string status_alumno { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual Semestre Semestre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoAlumno> CursoAlumno { get; set; }
    }
}
