//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escolapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.CursoAlumno = new HashSet<CursoAlumno>();
        }
    
        public int id_curso { get; set; }
        public int id_maestro { get; set; }
        public int id_materia { get; set; }
        public int id_semestre { get; set; }
        public int id_especialidad { get; set; }
        public string status_curso { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual Maestro Maestro { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual Semestre Semestre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoAlumno> CursoAlumno { get; set; }
    }
}
