//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escolapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoAlumno
    {
        public int id_cursoalumno { get; set; }
        public int id_curso { get; set; }
        public int id_alumno { get; set; }
        public string status_cursoAlumno { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
