//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escolapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maestro()
        {
            this.Curso = new HashSet<Curso>();
        }
    
        public int id_maestro { get; set; }
        public string nombre_maestro { get; set; }
        public string apellido_maestro { get; set; }
        public string direccion_maestro { get; set; }
        public int edad_maestro { get; set; }
        public string sexo_maestro { get; set; }
        public string telefono_maestro { get; set; }
        public System.DateTime fecha_registro_maestro { get; set; }
        public string status_maestro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Curso> Curso { get; set; }
    }
}
