//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escolapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EscuelaBd : DbContext
    {
        public EscuelaBd()
            : base("name=EscuelaBd")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<CursoAlumno> CursoAlumno { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<Maestro> Maestro { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<Semestre> Semestre { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual int sp_AltaAlumno(Nullable<int> id_alumno)
        {
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AltaAlumno", id_alumnoParameter);
        }
    
        public virtual int sp_AltaCurso(Nullable<int> id_curso)
        {
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AltaCurso", id_cursoParameter);
        }
    
        public virtual int sp_AltaCursoAlumno(Nullable<int> id_curso_alumno)
        {
            var id_curso_alumnoParameter = id_curso_alumno.HasValue ?
                new ObjectParameter("id_curso_alumno", id_curso_alumno) :
                new ObjectParameter("id_curso_alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AltaCursoAlumno", id_curso_alumnoParameter);
        }
    
        public virtual int sp_AltaEspecialidad(Nullable<int> id_especialidad)
        {
            var id_especialidadParameter = id_especialidad.HasValue ?
                new ObjectParameter("id_especialidad", id_especialidad) :
                new ObjectParameter("id_especialidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AltaEspecialidad", id_especialidadParameter);
        }
    
        public virtual int sp_AltaMaestro(Nullable<int> id_maestro)
        {
            var id_maestroParameter = id_maestro.HasValue ?
                new ObjectParameter("id_maestro", id_maestro) :
                new ObjectParameter("id_maestro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AltaMaestro", id_maestroParameter);
        }
    
        public virtual int sp_AltaMateria(Nullable<int> id_materia)
        {
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AltaMateria", id_materiaParameter);
        }
    
        public virtual int sp_AltaSemestre(Nullable<int> id_semestre)
        {
            var id_semestreParameter = id_semestre.HasValue ?
                new ObjectParameter("id_semestre", id_semestre) :
                new ObjectParameter("id_semestre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AltaSemestre", id_semestreParameter);
        }
    
        public virtual int sp_BajaAlumno(Nullable<int> id_alumno)
        {
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BajaAlumno", id_alumnoParameter);
        }
    
        public virtual int sp_BajaCurso(Nullable<int> id_curso)
        {
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BajaCurso", id_cursoParameter);
        }
    
        public virtual int sp_BajaCursoAlumno(Nullable<int> id_curso_alumno)
        {
            var id_curso_alumnoParameter = id_curso_alumno.HasValue ?
                new ObjectParameter("id_curso_alumno", id_curso_alumno) :
                new ObjectParameter("id_curso_alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BajaCursoAlumno", id_curso_alumnoParameter);
        }
    
        public virtual int sp_BajaEspecialidad(Nullable<int> id_especialidad)
        {
            var id_especialidadParameter = id_especialidad.HasValue ?
                new ObjectParameter("id_especialidad", id_especialidad) :
                new ObjectParameter("id_especialidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BajaEspecialidad", id_especialidadParameter);
        }
    
        public virtual int sp_BajaMaestro(Nullable<int> id_maestro)
        {
            var id_maestroParameter = id_maestro.HasValue ?
                new ObjectParameter("id_maestro", id_maestro) :
                new ObjectParameter("id_maestro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BajaMaestro", id_maestroParameter);
        }
    
        public virtual int sp_BajaMateria(Nullable<int> id_materia)
        {
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BajaMateria", id_materiaParameter);
        }
    
        public virtual int sp_BajaSemestre(Nullable<int> id_semestre)
        {
            var id_semestreParameter = id_semestre.HasValue ?
                new ObjectParameter("id_semestre", id_semestre) :
                new ObjectParameter("id_semestre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BajaSemestre", id_semestreParameter);
        }
    
        public virtual int sp_CrearCurso(Nullable<int> id_maestro, Nullable<int> id_materia, Nullable<int> id_semestre, Nullable<int> id_especialidad, string status_curso)
        {
            var id_maestroParameter = id_maestro.HasValue ?
                new ObjectParameter("id_maestro", id_maestro) :
                new ObjectParameter("id_maestro", typeof(int));
    
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            var id_semestreParameter = id_semestre.HasValue ?
                new ObjectParameter("id_semestre", id_semestre) :
                new ObjectParameter("id_semestre", typeof(int));
    
            var id_especialidadParameter = id_especialidad.HasValue ?
                new ObjectParameter("id_especialidad", id_especialidad) :
                new ObjectParameter("id_especialidad", typeof(int));
    
            var status_cursoParameter = status_curso != null ?
                new ObjectParameter("status_curso", status_curso) :
                new ObjectParameter("status_curso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CrearCurso", id_maestroParameter, id_materiaParameter, id_semestreParameter, id_especialidadParameter, status_cursoParameter);
        }
    
        public virtual int sp_CrearCursoAlumno(Nullable<int> id_curso, Nullable<int> id_alumno, string status_cursoAlumno)
        {
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            var status_cursoAlumnoParameter = status_cursoAlumno != null ?
                new ObjectParameter("status_cursoAlumno", status_cursoAlumno) :
                new ObjectParameter("status_cursoAlumno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CrearCursoAlumno", id_cursoParameter, id_alumnoParameter, status_cursoAlumnoParameter);
        }
    
        public virtual int sp_EditarAlumno(Nullable<int> id_alumno, Nullable<int> id_semestre, Nullable<int> id_especialidad, string nombre_alumno, string apellido_alumno, string direccion_alumno, Nullable<int> edad_alumno, string sexo_alumno, string telefono_alumno)
        {
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            var id_semestreParameter = id_semestre.HasValue ?
                new ObjectParameter("id_semestre", id_semestre) :
                new ObjectParameter("id_semestre", typeof(int));
    
            var id_especialidadParameter = id_especialidad.HasValue ?
                new ObjectParameter("id_especialidad", id_especialidad) :
                new ObjectParameter("id_especialidad", typeof(int));
    
            var nombre_alumnoParameter = nombre_alumno != null ?
                new ObjectParameter("nombre_alumno", nombre_alumno) :
                new ObjectParameter("nombre_alumno", typeof(string));
    
            var apellido_alumnoParameter = apellido_alumno != null ?
                new ObjectParameter("apellido_alumno", apellido_alumno) :
                new ObjectParameter("apellido_alumno", typeof(string));
    
            var direccion_alumnoParameter = direccion_alumno != null ?
                new ObjectParameter("direccion_alumno", direccion_alumno) :
                new ObjectParameter("direccion_alumno", typeof(string));
    
            var edad_alumnoParameter = edad_alumno.HasValue ?
                new ObjectParameter("edad_alumno", edad_alumno) :
                new ObjectParameter("edad_alumno", typeof(int));
    
            var sexo_alumnoParameter = sexo_alumno != null ?
                new ObjectParameter("sexo_alumno", sexo_alumno) :
                new ObjectParameter("sexo_alumno", typeof(string));
    
            var telefono_alumnoParameter = telefono_alumno != null ?
                new ObjectParameter("telefono_alumno", telefono_alumno) :
                new ObjectParameter("telefono_alumno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditarAlumno", id_alumnoParameter, id_semestreParameter, id_especialidadParameter, nombre_alumnoParameter, apellido_alumnoParameter, direccion_alumnoParameter, edad_alumnoParameter, sexo_alumnoParameter, telefono_alumnoParameter);
        }
    
        public virtual int sp_EditarCurso(Nullable<int> id_curso, Nullable<int> id_maestro, Nullable<int> id_materia, Nullable<int> id_semestre, Nullable<int> id_especialidad, string status_curso)
        {
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            var id_maestroParameter = id_maestro.HasValue ?
                new ObjectParameter("id_maestro", id_maestro) :
                new ObjectParameter("id_maestro", typeof(int));
    
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            var id_semestreParameter = id_semestre.HasValue ?
                new ObjectParameter("id_semestre", id_semestre) :
                new ObjectParameter("id_semestre", typeof(int));
    
            var id_especialidadParameter = id_especialidad.HasValue ?
                new ObjectParameter("id_especialidad", id_especialidad) :
                new ObjectParameter("id_especialidad", typeof(int));
    
            var status_cursoParameter = status_curso != null ?
                new ObjectParameter("status_curso", status_curso) :
                new ObjectParameter("status_curso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditarCurso", id_cursoParameter, id_maestroParameter, id_materiaParameter, id_semestreParameter, id_especialidadParameter, status_cursoParameter);
        }
    
        public virtual int sp_EditarCursoAlumno(Nullable<int> id_curso_alumno, Nullable<int> id_curso, Nullable<int> id_alumno)
        {
            var id_curso_alumnoParameter = id_curso_alumno.HasValue ?
                new ObjectParameter("id_curso_alumno", id_curso_alumno) :
                new ObjectParameter("id_curso_alumno", typeof(int));
    
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditarCursoAlumno", id_curso_alumnoParameter, id_cursoParameter, id_alumnoParameter);
        }
    
        public virtual int sp_EditarEspecialidad(Nullable<int> id_Especialidad, string nombre_Especialidad)
        {
            var id_EspecialidadParameter = id_Especialidad.HasValue ?
                new ObjectParameter("id_Especialidad", id_Especialidad) :
                new ObjectParameter("id_Especialidad", typeof(int));
    
            var nombre_EspecialidadParameter = nombre_Especialidad != null ?
                new ObjectParameter("nombre_Especialidad", nombre_Especialidad) :
                new ObjectParameter("nombre_Especialidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditarEspecialidad", id_EspecialidadParameter, nombre_EspecialidadParameter);
        }
    
        public virtual int sp_EditarMaestro(Nullable<int> id_maestro, string nombre_maestro, string apellido_maestro, string direccion_maestro, Nullable<int> edad_maestro, string sexo_maestro, string telefono_maestro)
        {
            var id_maestroParameter = id_maestro.HasValue ?
                new ObjectParameter("id_maestro", id_maestro) :
                new ObjectParameter("id_maestro", typeof(int));
    
            var nombre_maestroParameter = nombre_maestro != null ?
                new ObjectParameter("nombre_maestro", nombre_maestro) :
                new ObjectParameter("nombre_maestro", typeof(string));
    
            var apellido_maestroParameter = apellido_maestro != null ?
                new ObjectParameter("apellido_maestro", apellido_maestro) :
                new ObjectParameter("apellido_maestro", typeof(string));
    
            var direccion_maestroParameter = direccion_maestro != null ?
                new ObjectParameter("direccion_maestro", direccion_maestro) :
                new ObjectParameter("direccion_maestro", typeof(string));
    
            var edad_maestroParameter = edad_maestro.HasValue ?
                new ObjectParameter("edad_maestro", edad_maestro) :
                new ObjectParameter("edad_maestro", typeof(int));
    
            var sexo_maestroParameter = sexo_maestro != null ?
                new ObjectParameter("sexo_maestro", sexo_maestro) :
                new ObjectParameter("sexo_maestro", typeof(string));
    
            var telefono_maestroParameter = telefono_maestro != null ?
                new ObjectParameter("telefono_maestro", telefono_maestro) :
                new ObjectParameter("telefono_maestro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditarMaestro", id_maestroParameter, nombre_maestroParameter, apellido_maestroParameter, direccion_maestroParameter, edad_maestroParameter, sexo_maestroParameter, telefono_maestroParameter);
        }
    
        public virtual int sp_EditarMateria(Nullable<int> id_materia, string nombre_materia, Nullable<int> creditos, string status_materia)
        {
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            var nombre_materiaParameter = nombre_materia != null ?
                new ObjectParameter("nombre_materia", nombre_materia) :
                new ObjectParameter("nombre_materia", typeof(string));
    
            var creditosParameter = creditos.HasValue ?
                new ObjectParameter("creditos", creditos) :
                new ObjectParameter("creditos", typeof(int));
    
            var status_materiaParameter = status_materia != null ?
                new ObjectParameter("status_materia", status_materia) :
                new ObjectParameter("status_materia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditarMateria", id_materiaParameter, nombre_materiaParameter, creditosParameter, status_materiaParameter);
        }
    
        public virtual int sp_EditarSemestre(Nullable<int> id_semestre, string nombre_semestre)
        {
            var id_semestreParameter = id_semestre.HasValue ?
                new ObjectParameter("id_semestre", id_semestre) :
                new ObjectParameter("id_semestre", typeof(int));
    
            var nombre_semestreParameter = nombre_semestre != null ?
                new ObjectParameter("nombre_semestre", nombre_semestre) :
                new ObjectParameter("nombre_semestre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditarSemestre", id_semestreParameter, nombre_semestreParameter);
        }
    
        public virtual int sp_InsertarAlumno(Nullable<int> id_semestre, Nullable<int> id_especialidad, string nombre_alumno, string apellido_alumno, string direccion_alumno, Nullable<int> edad_alumno, string sexo_alumno, string telefono_alumno, string status_alumno)
        {
            var id_semestreParameter = id_semestre.HasValue ?
                new ObjectParameter("id_semestre", id_semestre) :
                new ObjectParameter("id_semestre", typeof(int));
    
            var id_especialidadParameter = id_especialidad.HasValue ?
                new ObjectParameter("id_especialidad", id_especialidad) :
                new ObjectParameter("id_especialidad", typeof(int));
    
            var nombre_alumnoParameter = nombre_alumno != null ?
                new ObjectParameter("nombre_alumno", nombre_alumno) :
                new ObjectParameter("nombre_alumno", typeof(string));
    
            var apellido_alumnoParameter = apellido_alumno != null ?
                new ObjectParameter("apellido_alumno", apellido_alumno) :
                new ObjectParameter("apellido_alumno", typeof(string));
    
            var direccion_alumnoParameter = direccion_alumno != null ?
                new ObjectParameter("direccion_alumno", direccion_alumno) :
                new ObjectParameter("direccion_alumno", typeof(string));
    
            var edad_alumnoParameter = edad_alumno.HasValue ?
                new ObjectParameter("edad_alumno", edad_alumno) :
                new ObjectParameter("edad_alumno", typeof(int));
    
            var sexo_alumnoParameter = sexo_alumno != null ?
                new ObjectParameter("sexo_alumno", sexo_alumno) :
                new ObjectParameter("sexo_alumno", typeof(string));
    
            var telefono_alumnoParameter = telefono_alumno != null ?
                new ObjectParameter("telefono_alumno", telefono_alumno) :
                new ObjectParameter("telefono_alumno", typeof(string));
    
            var status_alumnoParameter = status_alumno != null ?
                new ObjectParameter("status_alumno", status_alumno) :
                new ObjectParameter("status_alumno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarAlumno", id_semestreParameter, id_especialidadParameter, nombre_alumnoParameter, apellido_alumnoParameter, direccion_alumnoParameter, edad_alumnoParameter, sexo_alumnoParameter, telefono_alumnoParameter, status_alumnoParameter);
        }
    
        public virtual int sp_InsertarEspecialidad(string nombre_Especialidad, string estado_Especialidad)
        {
            var nombre_EspecialidadParameter = nombre_Especialidad != null ?
                new ObjectParameter("nombre_Especialidad", nombre_Especialidad) :
                new ObjectParameter("nombre_Especialidad", typeof(string));
    
            var estado_EspecialidadParameter = estado_Especialidad != null ?
                new ObjectParameter("estado_Especialidad", estado_Especialidad) :
                new ObjectParameter("estado_Especialidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarEspecialidad", nombre_EspecialidadParameter, estado_EspecialidadParameter);
        }
    
        public virtual int sp_InsertarMaestro(string nombre_maestro, string apellido_maestro, string direccion_maestro, Nullable<int> edad_maestro, string sexo_maestro, string telefono_maestro, string status_maestro)
        {
            var nombre_maestroParameter = nombre_maestro != null ?
                new ObjectParameter("nombre_maestro", nombre_maestro) :
                new ObjectParameter("nombre_maestro", typeof(string));
    
            var apellido_maestroParameter = apellido_maestro != null ?
                new ObjectParameter("apellido_maestro", apellido_maestro) :
                new ObjectParameter("apellido_maestro", typeof(string));
    
            var direccion_maestroParameter = direccion_maestro != null ?
                new ObjectParameter("direccion_maestro", direccion_maestro) :
                new ObjectParameter("direccion_maestro", typeof(string));
    
            var edad_maestroParameter = edad_maestro.HasValue ?
                new ObjectParameter("edad_maestro", edad_maestro) :
                new ObjectParameter("edad_maestro", typeof(int));
    
            var sexo_maestroParameter = sexo_maestro != null ?
                new ObjectParameter("sexo_maestro", sexo_maestro) :
                new ObjectParameter("sexo_maestro", typeof(string));
    
            var telefono_maestroParameter = telefono_maestro != null ?
                new ObjectParameter("telefono_maestro", telefono_maestro) :
                new ObjectParameter("telefono_maestro", typeof(string));
    
            var status_maestroParameter = status_maestro != null ?
                new ObjectParameter("status_maestro", status_maestro) :
                new ObjectParameter("status_maestro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarMaestro", nombre_maestroParameter, apellido_maestroParameter, direccion_maestroParameter, edad_maestroParameter, sexo_maestroParameter, telefono_maestroParameter, status_maestroParameter);
        }
    
        public virtual int sp_InsertarMateria(string nombre_materia, Nullable<int> creditos, string status_materia)
        {
            var nombre_materiaParameter = nombre_materia != null ?
                new ObjectParameter("nombre_materia", nombre_materia) :
                new ObjectParameter("nombre_materia", typeof(string));
    
            var creditosParameter = creditos.HasValue ?
                new ObjectParameter("creditos", creditos) :
                new ObjectParameter("creditos", typeof(int));
    
            var status_materiaParameter = status_materia != null ?
                new ObjectParameter("status_materia", status_materia) :
                new ObjectParameter("status_materia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarMateria", nombre_materiaParameter, creditosParameter, status_materiaParameter);
        }
    
        public virtual ObjectResult<sp_ListarAlumno_Result> sp_ListarAlumno()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarAlumno_Result>("sp_ListarAlumno");
        }
    
        public virtual ObjectResult<sp_ListarCursosADetalle_Result> sp_ListarCursosADetalle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCursosADetalle_Result>("sp_ListarCursosADetalle");
        }
    
        public virtual ObjectResult<sp_ListarCursosAlumno_Result> sp_ListarCursosAlumno()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCursosAlumno_Result>("sp_ListarCursosAlumno");
        }
    
        public virtual ObjectResult<sp_ListarEspecialidades_Result> sp_ListarEspecialidades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarEspecialidades_Result>("sp_ListarEspecialidades");
        }
    
        public virtual ObjectResult<sp_ListarMaestro_Result> sp_ListarMaestro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarMaestro_Result>("sp_ListarMaestro");
        }
    
        public virtual ObjectResult<sp_ListarMateria_Result> sp_ListarMateria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarMateria_Result>("sp_ListarMateria");
        }
    
        public virtual ObjectResult<sp_ListarSemestres_Result> sp_ListarSemestres()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarSemestres_Result>("sp_ListarSemestres");
        }
    
        public virtual ObjectResult<sp_Login_Result> sp_Login(string correo_usuario, string password_usuario)
        {
            var correo_usuarioParameter = correo_usuario != null ?
                new ObjectParameter("correo_usuario", correo_usuario) :
                new ObjectParameter("correo_usuario", typeof(string));
    
            var password_usuarioParameter = password_usuario != null ?
                new ObjectParameter("password_usuario", password_usuario) :
                new ObjectParameter("password_usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Login_Result>("sp_Login", correo_usuarioParameter, password_usuarioParameter);
        }
    
        public virtual int sp_RegistrarSemestre(string nombre_semestre, string status_semestre)
        {
            var nombre_semestreParameter = nombre_semestre != null ?
                new ObjectParameter("nombre_semestre", nombre_semestre) :
                new ObjectParameter("nombre_semestre", typeof(string));
    
            var status_semestreParameter = status_semestre != null ?
                new ObjectParameter("status_semestre", status_semestre) :
                new ObjectParameter("status_semestre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarSemestre", nombre_semestreParameter, status_semestreParameter);
        }
    }
}
